### ISSUE TITLE
documentation for applying to to a new protein

### ISSUE THREAD

**Issue by peterthorpe5** [BojarLab/LectinOracle#2]
Dear LectinOracle,

Thank you for your software

I would like to apply your method to a new protein I have been asked to look into. Would it be possible for more indepth how to guide? I see in you .ipynb there is a section "Legacy: Getting ESM-1b representations for new lectins" 

Would this section apply to a new protein? If so, what would be the input file and format for a new protein? Which line of code could I alter to input my new protein of interest?

Regards,

Pete

**Comment by pvalle6** [comment]
Hey Pete, 

It seems that the functionality of LectinOracle in this repository has been continued in the https://github.com/BojarLab/glycowork repository. If you would open a issue thread in that repository, I would gladly help you with ESM-1b Representations for new proteins. 

I opened my own thread at https://github.com/BojarLab/LectinOracle/issues/1 and was recommended glycowork and have ran without issues every since.

Peter

**Comment by peterthorpe5** [comment]
Thank you very much for taking the time to respond to me. I will have a good go through the docs before opening an issue. 

Thanks again,

Pete
